#!/bin/sh

# script called when status 'closed' is set
# parameters: text_name version1_name version2_name old_status alignment_id responsible_userid editor_userid
# old_status can be 'open', 'finished', 'closed' or 'blocked'
# last line written to STDOUT will be showed to the used as 'WARNING'

#echo "alignment of text '$1', version '$2' and '$3' (with id '$5') changed status from '$4' to 'closed', responsible userid: $6, editor userid: $7" >/tmp/report.txt

### Export all files to $OUT_DIR
#OUT_DIR=/tmp
#cli/export -f xml_links:ic aid $5 >$OUT_DIR/$1.$2_$3.aln.xml
#cli/export -f orig:ic t1aid $5 >$OUT_DIR/$1.$2.xml
#cli/export -f orig:ic t2aid $5 >$OUT_DIR/$1.$3.xml

#echo "Error message to show to the user."
